Fix lots of issues

diff --git a/.github/workflows/pr-verify.yaml b/.github/workflows/pr-verify.yaml
--- a/.github/workflows/pr-verify.yaml
+++ b/.github/workflows/pr-verify.yaml
@@ -9,13 +9,19 @@ on:
       - "requests/*.csv"
 
 jobs:
-  update-db:
+  verify:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout codebase
         uses: actions/checkout@v3
         with:
           fetch-depth: 2
+
+      - name: Check request filenames
+        uses: batista/lint-filenames@v1
+        with:
+          path: './requests'
+          pattern: "^[-_.A-Za-z0-9]*$"
 
       - uses: robinraju/release-downloader@v1.4
         with:
@@ -33,6 +39,14 @@ jobs:
       - name: Verify
         run: |
           chmod +x ./accounter-exe/accounter
-          CHANGED=$(printf %b '${{ steps.changed-files.outputs.all_changed_files }}' | xargs -d '\n')
-          ./accounter-exe/accounter --database ./account.sqlite --filename "$CHANGED" --user ${{ github.event.pull_request.user.login }} --validate
+
+          CHANGED=$(printf %b '${{ steps.changed-files.outputs.all_changed_files }}')
+          NUM_CHANGED=$(echo "$CHANGED" | wc -l)
+          if [ $NUM_CHANGED -ne 1 ]; then
+            echo "::error Too many files - only submit one file"
+            exit 1
+          fi
+          CHANGED_ARGS=$(echo "$CHANGED" | xargs -d '\n')
+
+          ./accounter-exe/accounter --database ./account.sqlite --filename "$CHANGED_ARGS" --user ${{ github.event.pull_request.user.login }} --validate
 
diff --git a/.github/workflows/update-db.yaml b/.github/workflows/update-db.yaml
--- a/.github/workflows/update-db.yaml
+++ b/.github/workflows/update-db.yaml
@@ -3,6 +3,7 @@ on:
   push:
     branches:
       - main
+      - test
     paths:
       - "requests/*.csv"
 
@@ -10,7 +11,7 @@ jobs:
   update-database:
     if: |
       github.event_name == 'push' &&
-      github.ref_name == 'main' &&
+      (github.ref_name == 'main' || github.ref_name == 'test') &&
       github.actor != 'nd-0r-test' &&
       github.event.repository.fork == false
     runs-on: ubuntu-latest
@@ -37,10 +38,20 @@ jobs:
       - name: Update database
         run: |
           chmod +x ./accounter-exe/accounter
+          git checkout '${{ github.ref_name }}'
           git config --global user.email "aorals2@illinois.edu"
           git config --global user.name "Andrew Orals"
-          CHANGED=$(printf %b '${{ steps.changed-files.outputs.all_changed_files }}' | xargs -d '\n')
-          ./accounter-exe/accounter --database ./account.sqlite --filename "$CHANGED" --user "$(git --no-pager log --pretty=format:'%an' --diff-filter=A -- ./LICENSE)" --markdown ./README.md > ./balance.csv
+
+          CHANGED=$(printf %b '${{ steps.changed-files.outputs.all_changed_files }}')
+          NUM_CHANGED=$(echo "$CHANGED" | wc -l)
+          if [ $NUM_CHANGED -ne 1 ]; then
+            echo "::error Too many files - only submit one file"
+            exit 1
+          fi
+          CHANGED_ARGS=$(echo "$CHANGED" | xargs -d '\n')
+          USERNAME=$(git --no-pager log --pretty=format:'%an' --diff-filter=A -- "$CHANGED_ARGS")
+          ./accounter-exe/accounter --database ./account.sqlite --filename "$CHANGED_ARGS" --user "$USERNAME" --markdown ./README.md > ./balance.csv
+
           git rm "$CHANGED"
           git add README.md balance.csv account.sqlite
           git commit -m "ACCOUNTANT: add transaction"
